---

# These tasks set up the VM to connect to the cluster


- name: Install Azure CLI
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

- name: Install pip
  apt:
    name: python3-pip
    state: present  

- name: Install Kubernetes Python client
  shell: sudo pip install kubernetes

- name: Install Kubectl
  shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Install Helm v3
  shell: sudo curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 &&
         chmod 700 get_helm.sh && ./get_helm.sh

- name: Login to Azure to use the CLI commands
  shell: az login --identity

- name: Get AKS cluster credentials
  shell: az aks get-credentials --name scaProjectAKS --resource-group sca-project

- name: Install azure-file-csi driver
  shell: curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v1.1.0/deploy/install-driver.sh | bash -s v1.5.0 --

- name: Install AKS preview CLI extensions
  shell: az extension add --name aks-preview

#- name: kubectl apply storage class
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('template', 'templates/storage-class-az-file.yaml.j2') | from_yaml }}"
