- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: project
    api_version: v1
    kind: Namespace
    state: present

- name: kubectl apply project
  kubernetes.core.k8s:
    state: present
    definition: "{{ item }}" 
  loop:
    - "{{ lookup('template', 'templates/frontend.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/dbsec.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/backend.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/frontend_service.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/backend_service.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/database_pvc.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/postgres.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/postgres_service.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/ingress.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/frontend_hpa.yaml') | from_yaml }}"
    - "{{ lookup('template', 'templates/backend_hpa.yaml') | from_yaml }}"
