- name: kubectl apply storage class
  kubernetes.core.k8s:
    state: present
    definition: 
    loop:
      - "{{ lookup('file', 'files/frontend.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/dbsec.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/backend.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/frontend_service.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/backend_service.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/database_pvc.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/postgres.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/postgres_service.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/ingress.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/frontend_hpa.yaml') | from_yaml }}"
      - "{{ lookup('file', 'files/backend_hpa.yaml') | from_yaml }}"