apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
