---

- name: Add the cert-manager repository
  kubernetes.core.helm_repository:
    name: "argo"
    repo_url: "https://argoproj.github.io/argo-helm"

- name: Deploy cert-manager chart
  kubernetes.core.helm:
    name: "argo-cd"
    chart_ref: "argo/argo-cd"
    chart_version: "{{ argocd_chart_version }}"
    values: "{{ lookup('template', 'templates/values.yaml.j2') | from_yaml }}"
    release_namespace: "argocd"
    create_namespace: true

- name: kubectl apply ingress
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/ingress.yaml.j2') | from_yaml }}"

- name: kubectl apply application set
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/application-set.yaml.j2') | from_yaml }}"
