---

- name: Add the cert-manager repository
  kubernetes.core.helm_repository:
    name: "cert-manager"
    repo_url: "https://charts.jetstack.io"

- name: Deploy cert-manager chart
  kubernetes.core.helm:
    name: "cert-manager"
    chart_ref: "cert-manager/cert-manager"
    chart_version: "{{ cert_manager_chart_version }}"
    release_namespace: "cert-manager"
    create_namespace: true
    values: "{{ lookup('template', 'templates/values.yaml.j2') | from_yaml }}"

- name: Retrieve cert-manager user identity client id to an environment variable
  shell: export USER_ASSIGNED_IDENTITY_CLIENT_ID=$(az identity show --name "cert-manager" --query 'clientId' -o tsv) > /dev/null
  delegate_to: localhost

- name: kubectl apply clusterissuer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/clusterissuer.yaml.j2') | from_yaml }}"
