---

- name: Add the cert-manager repository
  kubernetes.core.helm_repository:
    name: "cert-manager"
    repo_url: "https://charts.jetstack.io"

- name: Deploy cert-manager chart
  kubernetes.core.helm:
    name: "cert-manager"
    chart_ref: "cert-manager/cert-manager"
    chart_version: "{{ cert-manager_chart_version }}"
    release_namespace: "cert-manager"
    create_namespace: true
    set_values: 
      - value: installCRDs=true
        value_type: string

- name: kubectl apply clusterissuer
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/deployment.yaml.j2') | from_yaml }}"