- name: Update Azure Firewall
  azure_rm_azurefirewall:
    resource_group: sca-project
    name: scaFW
    nat_rule_collections:
      - priority: 100
        action:
          type: dnat
        rules:
          - name: DNAT-HTTPS-traffic
            description: D-NAT all outbound web traffic for inspection
            source_addresses:
              - '*'
            destination_addresses:
              - '{{ firewall_ip }}'
            destination_ports:
              - '443'
            protocols:
              - tcp
            translated_address: '{{ ingress_ip }}'
            translated_port: '443'
          - name: DNAT-HTTP-traffic
            description: D-NAT all outbound web traffic for inspection
            source_addresses:
              - '*'
            destination_addresses:
              - '{{ firewall_ip }}'
            destination_ports:
              - '80'
            protocols:
              - tcp
            translated_address: '{{ ingress_ip }}'
            translated_port: '80'
        name: natrulecoll

- name: createCNAME record
  azure_rm_dnsrecordset:
    resource_group: domain
    relative_name: "{{ item.subdomain }}"
    zone_name: "{{ domain }}"
    record_type: "{{ item.record_type }}"
    records: "{{ firewall_ip }}"
  loop:
      - {subdomain: '{{ app_subdomain }}', record_type: 'A'}
      - {subdomain: '{{ argocd_subdomain }}', record_type: 'A'}