---
# This runs the entire playbook

- hosts: all
  pre_tasks:
    - name: update cache
      apt:
        update_cache: yes
  roles:
    - name: Configure the VM
      role: aks-tools
    - name: Configure Nginx ingress controller
      role: nginx-ingress-controller
    - name: Configure DNS
      role: dns
    - name: Configure cert-manager
      role: cert-manager
    - name: Configure ArgoCD
      role: argocd