---
# This runs the entire playbook

- hosts: all
  pre_tasks:
    - name: update cache
      apt:
        update_cache: yes
  roles:
    - name: Configure the AKS through the VM
      role: aks-tools
    - name: Configure Nginx ingress controller
      role: nginx-ingress-controller
    - name: Deploy the application
      role: deploy
