version: '3.9'
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432
    
    environment:
      TZ: "${POSTGRES_TZ}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    
    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./eatfoodfrontend
      dockerfile: Dockerfile
    
    environment:
      WDS_SOCKET_PORT: ${FRONTEND_EXPOSE_PORT}
    
    ports:
      - ${FRONTEND_EXPOSE_PORT}:3000
    
    volumes:
      - ./eatfoodfrontend:/app/frontend
      - /app/frontend/node_modules

    depends_on:
      - backend

  backend: 
    build: 
      context: ./eatfoodbackend
      dockerfile: Dockerfile
    
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
    
    ports:
      - ${DJANGO_EXPOSE_PORT}:8000

    volumes:
      - ./eatfoodbackend:/app/backend

    depends_on:
      - db
