on:
  push:
    branches: [ master ]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  build-images:
    runs-on: ubuntu-latest
    environment: testrun
    env:
      DOCKER_REPOSITORY: sayaligbe 
      FRONTEND_IMAGE_NAME: sca-frontend
      BACKEND_IMAGE_NAME: sca-backend
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      SUB_ID: ${{ secrets.SUB_ID }}
      SSH: ${{ secrets.SSH }}

    steps:

    - name: Add mask to hide secrets 
      run: |
        echo "::add-mask::$SUB_ID"
        echo "::add-mask::$SSH"

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Build Docker images
      run: |
        docker build source-code/client --file source-code/client/Dockerfile  --tag $DOCKER_REPOSITORY/$FRONTEND_IMAGE_NAME:$IMAGE_TAG --no-cache
        docker build source-code/client --file source-code/client/Dockerfile  --tag $DOCKER_REPOSITORY/$BACKEND_IMAGE_NAME:$IMAGE_TAG --no-cache

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Image to Docker Hub
      run: |
        docker push $DOCKER_REPOSITORY/$FRONTEND_IMAGE_NAME:$IMAGE_TAG
        docker push $DOCKER_REPOSITORY/$BACKEND_IMAGE_NAME:$IMAGE_TAG

    - name: Update the docker images in the kubernetes manifests
      run: |
        sed -i '/^frontendImg:.*/ s//frontendImg:$DOCKER_REPOSITORY\/$FRONTEND_IMAGE_NAME:$IMAGE_TAG/' infrastructure-addons/group_vars/all/vars.yml
        sed -i '/^backendImg:.*/ s//backendImg:$DOCKER_REPOSITORY\/$BACKEND_IMAGE_NAME:$IMAGE_TAG/' infrastructure-addons/group_vars/all/vars.yml

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#provision infrastructure
        
    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
        
#Provision infrastructure

    - name: Terraform init
      id: init
      run: |
        cd infrastructure
        terraform init 
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

    - name: Terraform plan
      id: plan
      run: |
        cd infrastructure
        terraform plan -var="ssh_public_key=${{ secrets.SSH }}" -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true
      
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: |
        cd infrastructure
        exit 1
      
    - name: Terraform apply
      id: apply
      run: |
        cd infrastructure
        terraform apply -var="ssh_public_key=${{ secrets.SSH }}" -auto-approve -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true

#deploy workload

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies Including Ansible
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: unnecessary
        if_key_exists: fail

    - name: run playbook
      run: |
        cd infrastructure-addons
        echo '${{ secrets.VAULT_PASSWORD }}' | ansible-playbook main.yml --vault-pass-file=/bin/cat 