---

- name: Add the ingress nginx repository
  kubernetes.core.helm_repository:
    name: "ingress-nginx"
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Deploy Nginx ingress chart
  kubernetes.core.helm:
    name: "nginx-ingress"
    chart_ref: "ingress-nginx/ingress-nginx"
    chart_version: "ingress_chart_version"
    values: "{{ lookup('template', 'templates/values.yaml.j2') | from_yaml }}"
    release_namespace: "nginx-ingress"
    create_namespace: true